# Change these first
owner: tripleerv # Your GitHub username
repo: dealer-api-status # Your GitHub repository name

# Add your sites here
sites:
  - name: LTV Dealer API
    url: https://dealer.api.leisurevans.com
  - name: LTV Owners API
    url: https://api.leisurevans.com
  - name: LTV Website
    url: https://leisurevans.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.triplee.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://tripleerv.com/wp-content/themes/tripleerv-wp/img/eee-logo-mobile.svg
  name: Triple E RV Status
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
